-- MySQL Script generated by MySQL Workbench
-- Sun Feb 11 19:57:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ConcertsDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ConcertsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ConcertsDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `ConcertsDB` ;

-- -----------------------------------------------------
-- Table `ConcertsDB`.`Concert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConcertsDB`.`Concert` (
  `idConcert` INT NULL AUTO_INCREMENT,
  `ConcertName` VARCHAR(45) NOT NULL,
  `InterpretName` VARCHAR(45) NOT NULL,
  `Place` VARCHAR(45) NOT NULL,
  `Time` DATETIME NOT NULL,
  PRIMARY KEY (`idConcert`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
